Implement homepage user interactions
tsuyokoya/vibify pull request #4
Opened 2022-05-10 19:12 UTC by tsuyokoya

This PR adds JavaScript functionality to update the "Playlist Title" and "Vibe" on the cassette image based on user inputs.

2022-05-16 10:15 UTC, ArfatSalman requested changes
Good work on using the PR system. Some commits are repeated in your PRs. We'll talk about it in our sessions. 

Keep working with the PR flow.

2022-05-16 10:15 UTC, ArfatSalman commented on app.py
> +    # print(client_id, redirect_uri, scope)
Leaving commented out code is generally regarded as a bad practice.

2022-05-16 10:15 UTC, ArfatSalman commented on app.py
> +        token_url = "https://accounts.spotify.com/api/token"
You can keep the `token_url` outside this function as this variable is not dependent on the function.

2022-05-16 10:15 UTC, ArfatSalman commented on app.py
> +        print("THIS IS THE POST RESPONSE", post_response.json())
At this stage, it's better to start using an actual logging library to udnerstand how different levels of logging works. Here's the link to the library: https://docs.python.org/3/library/logging.html

Flask logging: https://flask.palletsprojects.com/en/2.1.x/logging/

2022-05-16 10:15 UTC, ArfatSalman commented on config.py
> +    CLIENT_SECRET = "c03961d990b3482c96c99b44431a7946"
If these are supposed to be public, you might want to put a comment saying "These are supposed to be public". Since the word `CLIENT_SECRET` is not evoking the right feelings. 😄

2022-05-16 10:15 UTC, ArfatSalman commented on spotify.py
> +    return "".join(random.choice(characters) for i in range(15))
Take the `15` in `range(15)` as argument (defaulted to 15), so that you can make the any length state key.

2022-05-16 10:15 UTC, ArfatSalman commented on spotify.py
> +    authorize_base_url = "https://accounts.spotify.com/en/authorize?"
Keep all the Spotify's URL in their own class or file or dict. Like this
```
class SpotifyURLs:
    BASE = '...',
    AUTHORIZATION = BASE + '\auth'
```

it makes it easier to see all the relevant urls in one place. You can also use dict.

2022-05-16 10:15 UTC, ArfatSalman commented on static/js/homepage.js
> +const playlist_title_input = document.querySelectorAll(".vibify-inputs")[0];
snake case in JS? 😅

2022-05-16 10:15 UTC, ArfatSalman commented on static/js/homepage.js
> +playlist_title_input.addEventListener("keyup", (e) => {
Take a look at this.

https://www.youtube.com/watch?v=jLqTXkFtEH0

2022-05-31 17:26 UTC, ArfatSalman approved these changes

2022-05-31 23:16 UTC, tsuyokoya commented on static/js/homepage.js
> +playlist_title_input.addEventListener("keyup", (e) => {
Updated event listener to be on "input" instead of "keyup"

https://github.com/tsuyokoya/vibify/pull/4/commits/55047f4332319cde6b37e782961d81e885d23f47

2022-05-31 23:27 UTC, tsuyokoya commented on spotify.py
> +    authorize_base_url = "https://accounts.spotify.com/en/authorize?"
Created a SpotifyAPI class in the "spotify-auth" branch.

https://github.com/tsuyokoya/vibify/pull/3

2022-06-02 00:01 UTC, merged